# Site settings
course_name: Big Data Processing (AI60004)
course_description: "The course gives a comprehensive introduction to storing and processing `big data’ using modern big data
systems such as Map-reduce and Spark that run on large commodity clusters. The primary focus is on
algorithm design and programming at `scale’ applied to all major domains: text, graph, streaming and
relational data. The course also introduces scalable machine learning algorithms using Spark. The course will
use Databricks cloud platform for hands-on demo. The students can use Databricks or any other cluster
computing framework for their assignments."

course_semester: "Spring,2022-23"

baseurl: "/bdp-ai60004" # the subpath of your site, e.g. /blog/
url: "http://ainimesh.github.io/" # the base hostname & protocol for your site

schoolname: "CoE-AI, IIT Kharagpur"
schoolurl: "http://www.ai.iitkgp.ac.in/"
#twitter_username: username 

address: |
    Center of Excellence in Artififial Intelligence
    IIT Kharagpur, 721302
    West Bengal, India

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"

theme: jekyll-theme-cayman
